import { useState } from 'react';

type OSType = 'macos' | 'linux' | 'windows';
type ShellType = 'zsh' | 'bash' | 'powershell';

export const SecurifyInstall = () => {
  const [os, setOs] = useState<OSType>('macos');
  const [shell, setShell] = useState<ShellType>('zsh');
  const [copied, setCopied] = useState<boolean>(false);

  const getInstallCommand = (): string => {
    if (os === 'windows') {
      return `iwr -useb https://securify.dev/install.ps1 | iex\n# securify --version`;
    }
    
    // macOS or Linux
    if (shell === 'powershell') {
      return `pwsh -c "curl -fsSL https://securify.dev/install.sh | sh"`;
    }
    
    return `curl -fsSL https://securify.dev/install.sh | sh\n# securify --version`;
  };

  const handleCopy = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await navigator.clipboard.writeText(getInstallCommand());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('failed to copy text', err);
    }
  };

  const [stagedOnly, setStagedOnly] = useState<boolean>(true);
  const [entropyThresholdVal, setEntropyThresholdVal] = useState<number>(4.5);
  const [failCommit, setFailCommit] = useState<boolean>(true);
  const [excludeLockFiles, setExcludeLockFiles] = useState<boolean>(true);
  const [hookCopied, setHookCopied] = useState<boolean>(false);

  const generatePreCommitScript = (): string => {
    const excludes = excludeLockFiles ? 'node_modules,dist,*.lock,*-lock.json' : 'node_modules,dist';
    return `#!/bin/sh
# .git/hooks/pre-commit
# generated by securify config manager

echo "🔍 running securify commit audit..."

if ! command -v securify &> /dev/null; then
    echo "⚠️ securify cli not found. skipping audit."
    exit 0
fi

securify scan \\
  --entropy=${entropyThresholdVal} \\
  --exclude="${excludes}" \\
  ${stagedOnly ? '--staged-only' : ''} \\
  ${failCommit ? '--fail-on-leak' : '--warn-only'}

if [ $? -ne 0 ]; then
    echo "❌ [securify] credentials detected. commit rejected."
    exit 1
fi

echo "✔ [securify] audit passed."
exit 0`;
  };

  const handleCopyHook = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await navigator.clipboard.writeText(generatePreCommitScript());
      setHookCopied(true);
      setTimeout(() => setHookCopied(false), 2000);
    } catch (err) {
      console.error('failed to copy hook text', err);
    }
  };

  return (
    <section className="bg-black min-h-screen py-28 px-6 md:px-12 relative overflow-hidden select-none">
      {/* Grid lines background */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#080808_1px,transparent_1px),linear-gradient(to_bottom,#080808_1px,transparent_1px)] bg-[size:4rem_4rem] pointer-events-none" />

      <div className="max-w-6xl mx-auto relative z-10">
        
        {/* Header */}
        <div className="max-w-3xl mb-12">
          <span className="inline-block bg-neutral-900 border border-white/10 rounded-full px-4 py-1 text-xs text-neutral-400 lowercase mb-4 tracking-wider">
            install cli
          </span>
          <h2 className="hero-title text-4xl md:text-5xl font-medium tracking-tight text-white lowercase mb-4">
            install compiler hooks.
          </h2>
          <p className="text-neutral-400 text-sm font-light lowercase leading-relaxed max-w-xl">
            select your development environment settings below to configure the native installation script command for your terminal shell.
          </p>
        </div>

        {/* Configuration Setup */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Settings Options (lg:col-span-5) */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* OS selection */}
            <div>
              <span className="block text-[10px] font-mono text-neutral-500 mb-2 lowercase">
                operating system
              </span>
              <div className="flex gap-2">
                {(['macos', 'linux', 'windows'] as OSType[]).map((osItem) => (
                  <button
                    key={osItem}
                    onClick={() => {
                      setOs(osItem);
                      if (osItem === 'windows') setShell('powershell');
                    }}
                    className={`flex-1 px-3 py-2 rounded-xl text-xs font-mono border transition-all lowercase ${
                      os === osItem
                        ? 'bg-white text-black border-white'
                        : 'bg-neutral-950 text-neutral-500 border-white/5 hover:text-white'
                    }`}
                  >
                    {osItem}
                  </button>
                ))}
              </div>
            </div>

            {/* Shell selection */}
            {os !== 'windows' && (
              <div>
                <span className="block text-[10px] font-mono text-neutral-500 mb-2 lowercase">
                  shell profile
                </span>
                <div className="flex gap-2">
                  {(['zsh', 'bash', 'powershell'] as ShellType[]).map((shItem) => (
                    <button
                      key={shItem}
                      onClick={() => setShell(shItem)}
                      className={`flex-1 px-3 py-2 rounded-xl text-xs font-mono border transition-all lowercase ${
                        shell === shItem
                          ? 'bg-white text-black border-white'
                          : 'bg-neutral-950 text-neutral-500 border-white/5 hover:text-white'
                      }`}
                    >
                      {shItem}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div className="bg-neutral-950/80 border border-white/5 rounded-2xl p-6 select-text text-neutral-400 text-xs font-light leading-relaxed lowercase space-y-2">
              <span className="font-mono text-white block select-none">system prerequisites:</span>
              <p>• git installed on system path</p>
              <p>• root access write privileges for binary directories (usr/local/bin)</p>
            </div>

          </div>

          {/* Code Window Display (lg:col-span-7) */}
          <div className="lg:col-span-7 bg-neutral-950 border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col">
            <div className="px-4 py-3 bg-neutral-900/50 border-b border-white/5 flex justify-between items-center select-none">
              <span className="text-[10px] font-mono text-neutral-500 lowercase">terminal console install</span>
              <span className="w-2 h-2 rounded-full bg-neutral-800"></span>
            </div>

            <div className="p-6 font-mono text-xs md:text-sm text-neutral-300 min-h-[160px] bg-black/40 flex flex-col justify-between">
              <pre className="select-text whitespace-pre-wrap break-all">{getInstallCommand()}</pre>
              
              <div className="flex justify-end pt-6 select-none">
                <button
                  onClick={handleCopy}
                  className="bg-white text-black hover:bg-neutral-200 px-4 py-2 rounded-xl text-xs font-mono font-medium transition-colors lowercase"
                >
                  {copied ? 'copied script!' : 'copy script'}
                </button>
              </div>
            </div>
          </div>

        </div>

        {/* Hook Customizer Section */}
        <div className="border-t border-white/5 pt-16 mt-16">
          <div className="max-w-3xl mb-8">
            <span className="inline-block bg-neutral-900 border border-white/10 rounded-full px-4 py-1 text-xs text-neutral-400 lowercase mb-4 tracking-wider">
              local integration
            </span>
            <h3 className="text-2xl font-medium text-white lowercase mb-2">
              git pre-commit hook wizard
            </h3>
            <p className="text-neutral-400 text-xs font-light lowercase leading-relaxed max-w-xl">
              configure parameters to generate a custom local hook script. save this inside your project directory at <code>.git/hooks/pre-commit</code>.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
            
            {/* Options Panel */}
            <div className="lg:col-span-5 space-y-6">
              {/* Staged Scan */}
              <div className="flex items-start gap-3 cursor-pointer select-none">
                <input
                  type="checkbox"
                  id="stagedOnly"
                  checked={stagedOnly}
                  onChange={() => setStagedOnly(!stagedOnly)}
                  className="w-4 h-4 rounded bg-black border border-white/10 checked:bg-white accent-white mt-0.5"
                />
                <div>
                  <label htmlFor="stagedOnly" className="text-xs font-mono text-white block lowercase cursor-pointer">staged files only</label>
                  <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">scans only files cached for commit to save scanning time.</p>
                </div>
              </div>

              {/* Lockfiles Bypass */}
              <div className="flex items-start gap-3 cursor-pointer select-none">
                <input
                  type="checkbox"
                  id="excludeLockFiles"
                  checked={excludeLockFiles}
                  onChange={() => setExcludeLockFiles(!excludeLockFiles)}
                  className="w-4 h-4 rounded bg-black border border-white/10 checked:bg-white accent-white mt-0.5"
                />
                <div>
                  <label htmlFor="excludeLockFiles" className="text-xs font-mono text-white block lowercase cursor-pointer">skip lockfiles & packages</label>
                  <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">bypasses package-lock.json, cargo.lock, yarn.lock to prevent false flags.</p>
                </div>
              </div>

              {/* Fail commit vs Warning only */}
              <div className="flex items-start gap-3 cursor-pointer select-none">
                <input
                  type="checkbox"
                  id="failCommit"
                  checked={failCommit}
                  onChange={() => setFailCommit(!failCommit)}
                  className="w-4 h-4 rounded bg-black border border-white/10 checked:bg-white accent-white mt-0.5"
                />
                <div>
                  <label htmlFor="failCommit" className="text-xs font-mono text-white block lowercase cursor-pointer">abort commit on leaks</label>
                  <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">strictly exits with status code 1 to reject git commit when secrets match.</p>
                </div>
              </div>

              {/* Entropy Threshold */}
              <div className="space-y-2">
                <div className="flex justify-between text-xs font-mono text-neutral-400 lowercase">
                  <span>entropy verification limit:</span>
                  <span className="text-white">{entropyThresholdVal} bits</span>
                </div>
                <input
                  type="range"
                  min="3.0"
                  max="7.0"
                  step="0.5"
                  value={entropyThresholdVal}
                  onChange={(e) => setEntropyThresholdVal(parseFloat(e.target.value))}
                  className="w-full h-1 bg-neutral-900 rounded-lg appearance-none cursor-pointer accent-white"
                />
              </div>
            </div>

            {/* Generated Script Window */}
            <div className="lg:col-span-7 bg-neutral-950 border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col justify-between min-h-[300px]">
              <div>
                <div className="px-4 py-3 bg-neutral-900/50 border-b border-white/5 flex justify-between items-center select-none">
                  <span className="text-[10px] font-mono text-neutral-500 lowercase">.git/hooks/pre-commit</span>
                  <span className="w-2 h-2 rounded-full bg-neutral-800"></span>
                </div>
                
                <pre className="p-6 font-mono text-[11px] md:text-xs text-neutral-300 overflow-x-auto leading-relaxed select-all">
                  {generatePreCommitScript()}
                </pre>
              </div>

              <div className="p-4 border-t border-white/5 bg-neutral-900/10 flex justify-end">
                <button
                  onClick={handleCopyHook}
                  className={`text-xs font-mono font-medium rounded-xl px-5 py-3 lowercase transition-all select-none ${
                    hookCopied 
                      ? 'bg-emerald-950 text-emerald-400 border border-emerald-500/20' 
                      : 'bg-white hover:bg-neutral-200 text-black'
                  }`}
                >
                  {hookCopied ? 'copied hook script!' : 'copy hook script'}
                </button>
              </div>
            </div>

          </div>
        </div>

      </div>
    </section>
  );
};
