import { useState } from 'react';

type OSType = 'macos' | 'linux' | 'windows';
type ShellType = 'zsh' | 'bash' | 'powershell';

export const SecurifyInstall = () => {
  const [os, setOs] = useState<OSType>('macos');
  const [shell, setShell] = useState<ShellType>('zsh');
  const [copied, setCopied] = useState<boolean>(false);

  // Hook configurator states
  const [stagedOnly, setStagedOnly] = useState<boolean>(true);
  const [entropyThresholdVal, setEntropyThresholdVal] = useState<number>(4.5);
  const [failCommit, setFailCommit] = useState<boolean>(true);
  const [excludeLockFiles, setExcludeLockFiles] = useState<boolean>(true);
  const [hookCopied, setHookCopied] = useState<boolean>(false);

  // CI/CD configurator states
  const [ciPlatform, setCiPlatform] = useState<'github' | 'gitlab'>('github');
  const [ciBranch, setCiBranch] = useState<string>('main');
  const [ciCopied, setCiCopied] = useState<boolean>(false);
  const [ciScanPush, setCiScanPush] = useState<boolean>(true);
  const [ciScanPR, setCiScanPR] = useState<boolean>(true);
  const [ciFailOnLeak, setCiFailOnLeak] = useState<boolean>(true);
  const [ciSlackAlerts, setCiSlackAlerts] = useState<boolean>(false);

  const getInstallCommand = (): string => {
    if (os === 'windows') {
      return `iwr -useb https://securify.gucluyumhe.dev/install.ps1 | iex\n# securify --version`;
    }
    
    // macOS or Linux
    if (shell === 'powershell') {
      return `pwsh -c "curl -fsSL https://securify.gucluyumhe.dev/install.sh | sh"`;
    }
    
    return `curl -fsSL https://securify.gucluyumhe.dev/install.sh | sh\n# securify --version`;
  };

  const handleCopy = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await navigator.clipboard.writeText(getInstallCommand());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('failed to copy text', err);
    }
  };

  const generatePreCommitScript = (): string => {
    const excludes = excludeLockFiles ? 'node_modules,dist,*.lock,*-lock.json' : 'node_modules,dist';
    return `#!/bin/sh
# .git/hooks/pre-commit
# generated by securify config manager

echo "[securify] running commit audit..."

if ! command -v securify &> /dev/null; then
    echo "[warning] securify cli not found. skipping audit."
    exit 0
fi

securify scan \\
  --entropy=${entropyThresholdVal} \\
  --exclude="${excludes}" \\
  ${stagedOnly ? '--staged-only' : ''} \\
  ${failCommit ? '--fail-on-leak' : '--warn-only'}

if [ $? -ne 0 ]; then
    echo "[error] credentials detected. commit rejected."
    exit 1
fi

echo "[success] audit passed."
exit 0`;
  };

  const handleCopyHook = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await navigator.clipboard.writeText(generatePreCommitScript());
      setHookCopied(true);
      setTimeout(() => setHookCopied(false), 2000);
    } catch (err) {
      console.error('failed to copy hook text', err);
    }
  };

  const generateCiYaml = (): string => {
    if (ciPlatform === 'github') {
      const triggers: string[] = [];
      if (ciScanPush) {
        triggers.push(`  push:\n    branches: [ "${ciBranch}" ]`);
      }
      if (ciScanPR) {
        triggers.push(`  pull_request:\n    branches: [ "${ciBranch}" ]`);
      }
      const triggerSection = triggers.length > 0 
        ? `on:\n${triggers.join('\n')}` 
        : `on:\n  push:\n    branches: [ "${ciBranch}" ]`; // fallback

      let slackStep = '';
      if (ciSlackAlerts) {
        slackStep = `\n
      - name: Send Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: \${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: 'Securify Scan Alert'
          SLACK_MESSAGE: 'securify detected credentials in branch ${ciBranch}!'`;
      }

      return `name: Securify Leak Scan
${triggerSection}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # scan entire git history

      - name: Execute Securify Audit
        uses: securify-cli/securify-action@v2
        with:
          fail-on-leak: ${ciFailOnLeak}
          entropy-limit: ${entropyThresholdVal}${slackStep}`;
    } else {
      // GitLab CI/CD config
      const rules: string[] = [];
      if (ciScanPush) {
        rules.push(`$CI_COMMIT_BRANCH == "${ciBranch}"`);
      }
      if (ciScanPR) {
        rules.push(`$CI_PIPELINE_SOURCE == "merge_request_event"`);
      }
      const triggerRule = rules.length > 0
        ? `  rules:\n    - if: '${rules.join(' || ')}'`
        : `  only:\n    - ${ciBranch}`;

      let slackAfterScript = '';
      if (ciSlackAlerts) {
        slackAfterScript = `\n  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "failed" ]; then
        curl -X POST -H 'Content-type: application/json' --data "{\\"text\\":\\"[securify] leak detected in $CI_COMMIT_REF_NAME!\\"}" $SLACK_WEBHOOK_URL
      fi`;
      }

      return `securify-audit:
  stage: test
  image: securify/cli:latest
  script:
    - securify scan --entropy=${entropyThresholdVal} ${ciFailOnLeak ? '--fail-on-leak' : '--warn-only'}
${triggerRule}${slackAfterScript}`;
    }
  };

  const handleCopyCi = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await navigator.clipboard.writeText(generateCiYaml());
      setCiCopied(true);
      setTimeout(() => setCiCopied(false), 2000);
    } catch (err) {
      console.error('failed to copy CI yaml', err);
    }
  };

  return (
    <section className="bg-black min-h-screen py-28 px-6 md:px-12 relative overflow-hidden select-none">
      {/* Grid lines background */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#080808_1px,transparent_1px),linear-gradient(to_bottom,#080808_1px,transparent_1px)] bg-[size:4rem_4rem] pointer-events-none" />

      <div className="max-w-6xl mx-auto relative z-10">
        
        {/* Header */}
        <div className="max-w-3xl mb-12">
          <span className="inline-block bg-neutral-900 border border-white/10 rounded-full px-4 py-1 text-xs text-neutral-400 lowercase mb-4 tracking-wider">
            install cli
          </span>
          <h2 className="hero-title text-4xl md:text-5xl font-medium tracking-tight text-white lowercase mb-4">
            install compiler hooks.
          </h2>
          <p className="text-neutral-400 text-sm font-light lowercase leading-relaxed max-w-xl">
            select your development environment settings below to configure the native installation script command for your terminal shell.
          </p>
        </div>

        {/* Configuration Setup */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Settings Options (lg:col-span-5) */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* OS selection */}
            <div>
              <span className="block text-[10px] font-mono text-neutral-500 mb-2 lowercase">
                operating system
              </span>
              <div className="flex gap-2">
                {(['macos', 'linux', 'windows'] as OSType[]).map((osItem) => (
                  <button
                    key={osItem}
                    onClick={() => {
                      setOs(osItem);
                      if (osItem === 'windows') setShell('powershell');
                    }}
                    className={`flex-1 px-3 py-2 rounded-xl text-xs font-mono border transition-all lowercase ${
                      os === osItem
                        ? 'bg-white text-black border-white'
                        : 'bg-neutral-950 text-neutral-500 border-white/5 hover:text-white'
                    }`}
                  >
                    {osItem}
                  </button>
                ))}
              </div>
            </div>

            {/* Shell selection */}
            {os !== 'windows' && (
              <div>
                <span className="block text-[10px] font-mono text-neutral-500 mb-2 lowercase">
                  shell profile
                </span>
                <div className="flex gap-2">
                  {(['zsh', 'bash', 'powershell'] as ShellType[]).map((shItem) => (
                    <button
                      key={shItem}
                      onClick={() => setShell(shItem)}
                      className={`flex-1 px-3 py-2 rounded-xl text-xs font-mono border transition-all lowercase ${
                        shell === shItem
                          ? 'bg-white text-black border-white'
                          : 'bg-neutral-950 text-neutral-500 border-white/5 hover:text-white'
                      }`}
                    >
                      {shItem}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div className="bg-neutral-950/80 border border-white/5 rounded-2xl p-6 select-text text-neutral-400 text-xs font-light leading-relaxed lowercase space-y-2">
              <span className="font-mono text-white block select-none">system prerequisites:</span>
              <p>• git installed on system path</p>
              <p>• root access write privileges for binary directories (usr/local/bin)</p>
            </div>

          </div>

          {/* Code Window Display (lg:col-span-7) */}
          <div className="lg:col-span-7 bg-neutral-950 border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col">
            <div className="px-4 py-3 bg-neutral-900/50 border-b border-white/5 flex justify-between items-center select-none">
              <span className="text-[10px] font-mono text-neutral-500 lowercase">terminal console install</span>
              <span className="w-2 h-2 rounded-full bg-neutral-800"></span>
            </div>

            <div className="p-6 font-mono text-xs md:text-sm text-neutral-300 min-h-[160px] bg-black/40 flex flex-col justify-between">
              <pre className="select-text whitespace-pre-wrap break-all">{getInstallCommand()}</pre>
              
              <div className="flex justify-end pt-6 select-none">
                <button
                  onClick={handleCopy}
                  className="bg-white text-black hover:bg-neutral-200 px-4 py-2 rounded-xl text-xs font-mono font-medium transition-colors lowercase"
                >
                  {copied ? 'copied script!' : 'copy script'}
                </button>
              </div>
            </div>
          </div>

        </div>

        {/* Hook Customizer Section */}
        <div className="border-t border-white/5 pt-16 mt-16">
          <div className="max-w-3xl mb-8">
            <span className="inline-block bg-neutral-900 border border-white/10 rounded-full px-4 py-1 text-xs text-neutral-400 lowercase mb-4 tracking-wider">
              local integration
            </span>
            <h3 className="text-2xl font-medium text-white lowercase mb-2">
              git pre-commit hook wizard
            </h3>
            <p className="text-neutral-400 text-xs font-light lowercase leading-relaxed max-w-xl">
              configure parameters to generate a custom local hook script. save this inside your project directory at <code>.git/hooks/pre-commit</code>.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
            
            {/* Options Panel */}
            <div className="lg:col-span-5 space-y-6">
              {/* Staged Scan */}
              <div className="flex items-start gap-3 select-none">
                <button
                  type="button"
                  id="stagedOnly"
                  onClick={() => setStagedOnly(!stagedOnly)}
                  className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                    stagedOnly 
                      ? 'bg-white border-white text-black font-bold' 
                      : 'bg-black border-white/20 text-transparent hover:border-white/40'
                  }`}
                  aria-checked={stagedOnly}
                  role="checkbox"
                >
                  {stagedOnly && (
                    <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                    </svg>
                  )}
                </button>
                <div onClick={() => setStagedOnly(!stagedOnly)} className="cursor-pointer">
                  <span className="text-xs font-mono text-white block lowercase">staged files only</span>
                  <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">scans only files cached for commit to save scanning time.</p>
                </div>
              </div>

              {/* Lockfiles Bypass */}
              <div className="flex items-start gap-3 select-none">
                <button
                  type="button"
                  id="excludeLockFiles"
                  onClick={() => setExcludeLockFiles(!excludeLockFiles)}
                  className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                    excludeLockFiles 
                      ? 'bg-white border-white text-black font-bold' 
                      : 'bg-black border-white/20 text-transparent hover:border-white/40'
                  }`}
                  aria-checked={excludeLockFiles}
                  role="checkbox"
                >
                  {excludeLockFiles && (
                    <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                    </svg>
                  )}
                </button>
                <div onClick={() => setExcludeLockFiles(!excludeLockFiles)} className="cursor-pointer">
                  <span className="text-xs font-mono text-white block lowercase">skip lockfiles & packages</span>
                  <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">bypasses package-lock.json, cargo.lock, yarn.lock to prevent false flags.</p>
                </div>
              </div>

              {/* Fail commit vs Warning only */}
              <div className="flex items-start gap-3 select-none">
                <button
                  type="button"
                  id="failCommit"
                  onClick={() => setFailCommit(!failCommit)}
                  className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                    failCommit 
                      ? 'bg-white border-white text-black font-bold' 
                      : 'bg-black border-white/20 text-transparent hover:border-white/40'
                  }`}
                  aria-checked={failCommit}
                  role="checkbox"
                >
                  {failCommit && (
                    <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                    </svg>
                  )}
                </button>
                <div onClick={() => setFailCommit(!failCommit)} className="cursor-pointer">
                  <span className="text-xs font-mono text-white block lowercase">abort commit on leaks</span>
                  <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">strictly exits with status code 1 to reject git commit when secrets match.</p>
                </div>
              </div>

              {/* Entropy Threshold */}
              <div className="space-y-2">
                <div className="flex justify-between text-xs font-mono text-neutral-400 lowercase">
                  <span>entropy verification limit:</span>
                  <span className="text-white">{entropyThresholdVal} bits</span>
                </div>
                <input
                  type="range"
                  min="3.0"
                  max="7.0"
                  step="0.5"
                  value={entropyThresholdVal}
                  onChange={(e) => setEntropyThresholdVal(parseFloat(e.target.value))}
                  className="w-full h-1 bg-neutral-900 rounded-lg appearance-none cursor-pointer accent-white"
                />
              </div>
            </div>

            {/* Generated Script Window */}
            <div className="lg:col-span-7 bg-neutral-950 border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col justify-between min-h-[300px]">
              <div>
                <div className="px-4 py-3 bg-neutral-900/50 border-b border-white/5 flex justify-between items-center select-none">
                  <span className="text-[10px] font-mono text-neutral-500 lowercase">.git/hooks/pre-commit</span>
                  <span className="w-2 h-2 rounded-full bg-neutral-800"></span>
                </div>
                
                <pre className="p-6 font-mono text-[11px] md:text-xs text-neutral-300 overflow-x-auto leading-relaxed select-all">
                  {generatePreCommitScript()}
                </pre>
              </div>

              <div className="p-4 border-t border-white/5 bg-neutral-900/10 flex justify-end">
                <button
                  onClick={handleCopyHook}
                  className={`text-xs font-mono font-medium rounded-xl px-5 py-3 lowercase transition-all select-none ${
                    hookCopied 
                      ? 'bg-emerald-950 text-emerald-400 border border-emerald-500/20' 
                      : 'bg-white hover:bg-neutral-200 text-black'
                  }`}
                >
                  {hookCopied ? 'copied hook script!' : 'copy hook script'}
                </button>
              </div>
            </div>

          </div>
        </div>

        {/* CI/CD Integration Section */}
        <div className="border-t border-white/5 pt-16 mt-16">
          <div className="max-w-3xl mb-8">
            <span className="inline-block bg-neutral-900 border border-white/10 rounded-full px-4 py-1 text-xs text-neutral-400 lowercase mb-4 tracking-wider">
              cloud pipelines
            </span>
            <h3 className="text-2xl font-medium text-white lowercase mb-2">
              CI/CD pipeline configurator
            </h3>
            <p className="text-neutral-400 text-xs font-light lowercase leading-relaxed max-w-xl">
              automatically scan repository pull requests and commits in remote environments before deployment builds start.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
            
            {/* CI/CD Settings */}
            <div className="lg:col-span-5 space-y-6">
              
              {/* Platform selection */}
              <div>
                <span className="block text-[10px] font-mono text-neutral-500 mb-2 lowercase">
                  ci/cd provider
                </span>
                <div className="flex gap-2">
                  <button
                    onClick={() => setCiPlatform('github')}
                    className={`flex-1 px-3 py-2 rounded-xl text-xs font-mono border transition-all lowercase ${
                      ciPlatform === 'github'
                        ? 'bg-white text-black border-white'
                        : 'bg-neutral-950 text-neutral-500 border-white/5 hover:text-white'
                    }`}
                  >
                    GitHub Actions
                  </button>
                  <button
                    onClick={() => setCiPlatform('gitlab')}
                    className={`flex-1 px-3 py-2 rounded-xl text-xs font-mono border transition-all lowercase ${
                      ciPlatform === 'gitlab'
                        ? 'bg-white text-black border-white'
                        : 'bg-neutral-950 text-neutral-500 border-white/5 hover:text-white'
                    }`}
                  >
                    GitLab CI/CD
                  </button>
                </div>
              </div>

              {/* Target Branch selection */}
              <div className="space-y-1.5">
                <span className="block text-[10px] font-mono text-neutral-500 lowercase">
                  target tracking branch
                </span>
                <input
                  type="text"
                  value={ciBranch}
                  onChange={(e) => setCiBranch(e.target.value.trim() || 'main')}
                  placeholder="e.g. main"
                  className="w-full bg-neutral-950 border border-white/5 rounded-xl px-4 py-2.5 text-xs text-white focus:outline-none focus:border-white/20 font-mono"
                />
              </div>

              {/* Checkboxes */}
              <div className="space-y-4 pt-2">
                {/* Scan on Push */}
                <div className="flex items-start gap-3 select-none">
                  <button
                    type="button"
                    onClick={() => setCiScanPush(!ciScanPush)}
                    className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                      ciScanPush 
                        ? 'bg-white border-white text-black font-bold' 
                        : 'bg-black border-white/20 text-transparent hover:border-white/40'
                    }`}
                    aria-checked={ciScanPush}
                    role="checkbox"
                  >
                    {ciScanPush && (
                      <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                      </svg>
                    )}
                  </button>
                  <div onClick={() => setCiScanPush(!ciScanPush)} className="cursor-pointer">
                    <span className="text-xs font-mono text-white block lowercase">scan on push</span>
                    <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">trigger security analysis on every branch push event.</p>
                  </div>
                </div>

                {/* Scan on PR */}
                <div className="flex items-start gap-3 select-none">
                  <button
                    type="button"
                    onClick={() => setCiScanPR(!ciScanPR)}
                    className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                      ciScanPR 
                        ? 'bg-white border-white text-black font-bold' 
                        : 'bg-black border-white/20 text-transparent hover:border-white/40'
                    }`}
                    aria-checked={ciScanPR}
                    role="checkbox"
                  >
                    {ciScanPR && (
                      <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                      </svg>
                    )}
                  </button>
                  <div onClick={() => setCiScanPR(!ciScanPR)} className="cursor-pointer">
                    <span className="text-xs font-mono text-white block lowercase">scan on pull request</span>
                    <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">trigger security analysis on pull request syncs and updates.</p>
                  </div>
                </div>

                {/* Fail on Leak */}
                <div className="flex items-start gap-3 select-none">
                  <button
                    type="button"
                    onClick={() => setCiFailOnLeak(!ciFailOnLeak)}
                    className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                      ciFailOnLeak 
                        ? 'bg-white border-white text-black font-bold' 
                        : 'bg-black border-white/20 text-transparent hover:border-white/40'
                    }`}
                    aria-checked={ciFailOnLeak}
                    role="checkbox"
                  >
                    {ciFailOnLeak && (
                      <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                      </svg>
                    )}
                  </button>
                  <div onClick={() => setCiFailOnLeak(!ciFailOnLeak)} className="cursor-pointer">
                    <span className="text-xs font-mono text-white block lowercase">block build on high severity</span>
                    <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">mark the build step as failed if any secret matches are identified.</p>
                  </div>
                </div>

                {/* Slack Notifications */}
                <div className="flex items-start gap-3 select-none">
                  <button
                    type="button"
                    onClick={() => setCiSlackAlerts(!ciSlackAlerts)}
                    className={`w-4 h-4 rounded flex items-center justify-center border transition-all shrink-0 mt-0.5 ${
                      ciSlackAlerts 
                        ? 'bg-white border-white text-black font-bold' 
                        : 'bg-black border-white/20 text-transparent hover:border-white/40'
                    }`}
                    aria-checked={ciSlackAlerts}
                    role="checkbox"
                  >
                    {ciSlackAlerts && (
                      <svg className="w-3 h-3 stroke-[3] stroke-current" fill="none" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                      </svg>
                    )}
                  </button>
                  <div onClick={() => setCiSlackAlerts(!ciSlackAlerts)} className="cursor-pointer">
                    <span className="text-xs font-mono text-white block lowercase">notify via slack</span>
                    <p className="text-[10px] text-neutral-500 lowercase leading-relaxed">send instant alerts to your team's slack channel when a scan fails.</p>
                  </div>
                </div>
              </div>

            </div>

            {/* Compiled YAML File Display */}
            <div className="lg:col-span-7 bg-neutral-950 border border-white/5 rounded-2xl overflow-hidden shadow-2xl flex flex-col justify-between min-h-[300px]">
              <div>
                <div className="px-4 py-3 bg-neutral-900/50 border-b border-white/5 flex justify-between items-center select-none">
                  <span className="text-[10px] font-mono text-neutral-500 lowercase">
                    {ciPlatform === 'github' ? '.github/workflows/securify.yml' : '.gitlab-ci.yml'}
                  </span>
                  <span className="w-2 h-2 rounded-full bg-neutral-800"></span>
                </div>
                
                <pre className="p-6 font-mono text-[11px] md:text-xs text-neutral-300 overflow-x-auto leading-relaxed select-all">
                  {generateCiYaml()}
                </pre>
              </div>

              <div className="p-4 border-t border-white/5 bg-neutral-900/10 flex justify-end">
                <button
                  onClick={handleCopyCi}
                  className={`text-xs font-mono font-medium rounded-xl px-5 py-3 lowercase transition-all select-none ${
                    ciCopied 
                      ? 'bg-emerald-950 text-emerald-400 border border-emerald-500/20' 
                      : 'bg-white hover:bg-neutral-200 text-black'
                  }`}
                >
                  {ciCopied ? 'copied workflow config!' : 'copy workflow config'}
                </button>
              </div>
            </div>

          </div>
        </div>

      </div>
    </section>
  );
};
